// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwwpuuimkcrwshwfjrbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13d3B1dWlta2Nyd3Nod2ZqcmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzA3ODgsImV4cCI6MjA2OTAwNjc4OH0.gPMoRlvQEGjdxLzntDRO93tvWLFTuFz2VE0aAM6r86c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});